###############################################
# monte_carlo.py config
##############################################

pickle_directory_name: 'results_8 storage'           # the directory where all the pickle files are stored

                                                # the various columns in the final csv to be saved, description:
                                                # true_xxx: number of times xxx should have been chosen
                                                # prediction, ransac, pca: number of times it was chosen
                                                # pca#, pred#, ran#: number of times bin number # was chosen
                                                # rmse_xxx: the resultant rmse of that compenent of that state
                                                # xxx_before or xxx_after: the quantity xxx before or after bias estimation
results_column_names: ['rmse_px', 'rmse_py', 'rmse_pz', 'rmse_omx', 'rmse_omy', 'rmse_omz', 'rmse_vdx', 'rmse_vdy', 'rmse_vdz', 'rmse_x_before', 'rmse_y_before', 'rmse_z_before', 'rmse_x_after', 'rmse_y_after', 'rmse_z_after', 'rmse_q']
master_file_columns: ['file_name', 'ransac_error', 'pca_error', 'prediction_error', 'perfect_metric_choice', 'short_metric_choice', 'number_of_points', 'points_diff', 'z_spread', 'x_spread', 'y_spread', 'pca_prev_diff', 'ransac_prev_diff', 'x_spread_diff', 'y_spread_diff', 'z_spread_diff', 'ransac_pca_diff', 'ransac_pred_diff', 'pca_pred_diff']
top_level_dir: ''                       # the folder where csv will be saved and where code is
results_file_name: 'monte_carlo_results_results_ml_8bd.csv'    # name of file containing all results
assignment_results_file_name: 'assignment_results_ml8bd'      # for the assigment exercise in analyze_parallel.py
machine_learning_data_file_path: 'combined_output.csv'
machine_learning_data_columns: ['file_name', 'ransac_error', 'pca_error', 'prediction_error', 'perfect_metric_choice', 'short_metric_choice', 'number_of_points', 'points_diff', 'z_spread', 'x_spread', 'y_spread', 'pca_prev_diff', 'ransac_prev_diff', 'x_spread_diff', 'y_spread_diff', 'z_spread_diff', 'ransac_pca_diff', 'ransac_pred_diff', 'pca_pred_diff']
machine_learning_model_file: 'models/perfect_metric_modelGRTD.pkl'
options: ''                                     # specifying 'p' will enable printing of some messages to console


#############################################
# Kalman filter config
############################################
ini_vel_guess: [0.1, 0.1, 0.1]                 # initial velocity state of KF in m/s
ini_ang_vel_guess: [0.1, 0.1, 0.1]             # initial angular velocity state of KF in rad/s
ini_orientation: [1., 0., 0., 0.]              # initial orientation of debris - assigned, quaternion
                                               # initial covariance matrix of KF
ini_covariance_guess: [0.25, 0.5, 0.25, 0.05, 0.05, 0.05, 0.01, 0.01, 0.01, 0.25, 0.5, 0.25, 0.25, 0.5, 0.25, 0.25]
                                               # initial process noise associated with various states: [qp, qv, qom, qp1, qq]
ini_process_noise_cov: [0.00000001, 0.00000005, 0.00000005, 0.05, 0.000005]
                                               # initial measurement noise associated with various states: [p, om, p1, q]
ini_meas_noise_cov: [0.005, 0.5, 1., 0.004]

# KF weight values for ISPKF portion
alpha: 0.1                                     # alpha beta kappa together determine spread of sigmapoints
beta: 2
kappa: 0
epsilon: 0.0000000001                          # small positive constant for ensuring proper Cholesky
tolerance: 0.01                                # tolerance above which iterations for the ISPKF are terminated



#########################################
# Kabsch config
########################################
moving_average_len: 100                        # number of iterations to average over
settling_time: 100                             # number of iterations before which Kabsch is not activated


##########################################
# Bias config
#########################################
start_time: 20                                 # time in seconds after which data collection for bias estimation begins
interval: 20                                   # time interval in seconds for gathering data
threshold: 0.05                                # initial threshold to remove frequencies obtained from crosstalk with baseband frequency
number_of_sinusoids: 2                         # number of sinusoids to use to fit the data
number_of_skips: 1                             # when choosing frequencies from frequency according to decreasing magnitude, skips this many frequencies


##########################################
# Heuristic config
#########################################
start: 100                                     # number of iterations before which heuristic is inactive
ransac_prediction_threshold: 20                # maximal difference in degrees between ransac and predicted orientations
pca_prediction_threshold: 20                   # maximal difference in degrees between pca and predicted orientations
ransac_pca_threshold: 15                       # maximal difference in degrees between ransac and pca orientations
previous_threshold_multiplier: 3               # multiplier X omega X delta t given maximal difference between current and previous measurements
true_orientation_difference: 15               # in degrees, value used to determine whether the correct choice for the algorithm was ransac, pca, predicted (for analysis purposes)
use_perfect_metric: False                      # for comparison
short_metric_thresh: 15                         # threshold angle in degrees for short metric


######################################
# Other config
#####################################
error_calc_start: 50                           # time in seconds after which rmse's begin being tabluated
